openapi: 3.0.1
info:
  title: "Dashed-case enum names with numeric components don't get converted properly"
  version: 1.0.0
paths:
  /foo:
    get:
      operationId: getFoo
      parameters:
        - $ref: "#/components/parameters/FooEnum"
      responses:
        204:
          description: OK
components:
  schemas:
    FooEnum:
      type: string
      enum:
        - foo-bar-1
        - baz-quux-2-flurb
#        - 3-moo-cow
  parameters:
    FooEnum:
      in: query
      name: FooEnum
      required: true
      schema:
        $ref: '#/components/schemas/FooEnum'
